### ISSUE TITLE
ページヘッダーのタブ切り替え時にタイトルが表示されなくなることがある

### ISSUE THREAD

**Issue by yu256** [taiyme/misskey#109]
## 💡 Summary

タブの切り替え時に稀にタイトルが表示されなくなる（PCでは再現なし）

## 🥰 Expected Behavior

![805FDA18-6F2E-44B0-AD2D-A594A3458C9A](https://user-images.githubusercontent.com/122450013/227260363-72b96c38-42ae-42ed-9178-cc4a84f76f02.jpeg)
表示される

## 🤬 Actual Behavior

![9916B709-1E33-495B-A27D-CD7A5371C9A2](https://user-images.githubusercontent.com/122450013/227260514-bc6f9c6e-bce7-463c-ac30-ad078d88fb78.jpeg)
稀に表示されない

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey version:
Your OS:
Your browser:

**Comment by taiyme** [comment]
「UIのアニメーションを減らす」は有効/無効どちらですか？

**Comment by yu256** [comment]
無効
