### ISSUE TITLE
frontend/backend/sw: プッシュ通知有効化など

### ISSUE THREAD

**Issue by yu256** [taiyme/misskey#116]
## 💡 Summary

iOS16.4のプッシュ通知許可ダイアログを出すことができない

## 🥰 Expected Behavior

![IMG_2136](https://user-images.githubusercontent.com/122450013/228133666-0e34e56b-be7c-453c-8ba7-cc7b06de0569.png)
プッシュ通知を有効化ボタンを押すことで許可を求めるダイアログが出る

## 関連？

https://github.com/misskey-dev/misskey/pull/9218
https://github.com/misskey-dev/misskey/commits/develop/packages/sw/src/scripts/create-notification.ts

**Comment by taiyme** [comment]
これかなり面倒くさいなあ

**Comment by yu256** [comment]
まったくできないことはなさそう（突然許可ダイアログが出ることがある）
だけど、通知内容がプッシュ通知の更新をしましたになるからcreate-notification.tsの上から三つの変更をする必要がありそう？(fastifyが混ざっているせいでどっちにしろめんどくさそう)

**Comment by yu256** [comment]
一番上はv12では必要なさそう？(リアクション通知も問題なく届いた)

**Comment by yu256** [comment]
完全解決ではないけど、ひとまず読めるようにはなる
応急処置として
