### ISSUE TITLE
通知欄でも長い投稿を畳む

### ISSUE THREAD

**Issue by cffnpwr** [taiyme/misskey#27]
## 💡 Summary
思慮深いウニみたいな長い投稿が通知欄に来ると通知欄を占領してしまう

## 🥰 Expected Behavior
普通の投稿と同じように畳んでほしい

## 🤬 Actual Behavior
通知欄を占領するウニ
![Screenshot_20230219-192047.png](https://user-images.githubusercontent.com/86540016/219942282-bc5db34e-47ed-48b2-b16b-43aa62a42b84.png)

**Comment by taiyme** [comment]
v13では1行に省略されるみたい

<img width="346" alt="スクリーンショット 2023-02-20 12 42 46" src="https://user-images.githubusercontent.com/53635909/220004512-52b23706-f8bc-47aa-83b1-7311fa71b442.png">
