### ISSUE TITLE
開発環境が動かない

### ISSUE THREAD

**Issue by cffnpwr** [taiyme/misskey#30]
## 💡 Summary
`pnpm dev`で開発環境が動かない

## 🥰 Expected Behavior
- `pnpm dev`で開発環境が起動する
- docker上で開発環境が動くとDBとかredisとかを別で用意する必要が無くて🉐かも
- tscは遅いのでswcを使う（backend）

## 🤬 Actual Behavior
backendのビルドがうまくいってなくて起動時にコケる

**Comment by cffnpwr** [comment]
私がなんとかする

**Comment by taiyme** [comment]
おねがいします

**Comment by cffnpwr** [comment]
[ここ](https://github.com/cffnpwr/misskey-taiy/tree/feature/fix-dev)で一応開発環境が動くようにはしたけど、フロントエンドのビルドが終わるまで無限にエラーが出続けて精神衛生上よくないのでなんとかする
