### ISSUE TITLE
絵文字ピッカーが出ている状態でリロードまたはなにもしないを押そうとするとリアクションを押してしまう

### ISSUE THREAD

**Issue by suiminn** [taiyme/misskey#321]
### 💡 概要

絵文字ピッカーが出ている状態でリロードまたはなにもしないを押そうとするとリアクションを押してしまう

![2024-11-29 08-26-42 1-web](https://github.com/user-attachments/assets/e5cea1ae-da61-40b2-bfe5-a25fe2f8135b)

### 🥰 予想される挙動

リロードまたはなにもしないを押すとその動作をする

### 🤬 実際の挙動

後ろにある絵文字ピッカーを押してしまう

### 📝 再現手順

1.
2.
3.

### 💻 フロントエンドの環境

- Model and OS of the device(s): iPhone 15 Pro, iOS 17.0
- Browser: Safari 17.0
- Server URL: submarin.online
- Misskey: 2024.10.1-taiyme.3

### 🛰 バックエンドの環境 (サーバー管理者向け)

- Installation Method or Hosting Service:
- Misskey:
- Node:
- PostgreSQL:
- Redis:
- OS and Architecture:

### この問題は自分で解決したいですか？

- [ ] はい、自分でパッチを当ててプルリクエストを作成します

**Comment by taiyme** [comment]
duplicate of misskey-dev/misskey#14523
