### ISSUE TITLE
Github ActionsでのDocker build and pushに1時間かかるので長過ぎる

### ISSUE THREAD

**Issue by cffnpwr** [taiyme/misskey#40]
## Summary
- QEMUを使ってARM64向けをビルドしているのでアホみたいに時間がかかる
- Self-hosted runnerを使いたいけどARM64のマシンはRPi3Bしかないので無理

**Comment by cffnpwr** [comment]
JSなんだからアーキテクチャ関係なく動くと思いきやre2, sharp, tfjsあたりのバックエンドで動いてる奴らがバイナリを実行してる。大体は`pnpm i`のときにダウンロードなりビルドなりをしているので`npm_config_arch=arm64`をしたり、`CC=aarch64-linux-gnu-gcc`したりするとlinux/arm64向けのバイナリを作ってくれる。

問題は
- re2
- tfjs-node

この2つはどうあがいてもarm64向けにビルドをしてくれない。
re2はまだましな方で`node-gyp rebuild --arch="arm64"`でなんとかなる。
tfjs-nodeに関してはインストール時のスクリプトで`os.arch()`を叩いてる。そんなことしないでくれ。（切実）

**Comment by cffnpwr** [comment]
![Screenshot from 2023-02-26 01-49-42](https://user-images.githubusercontent.com/86540016/221369406-b1bb4d1d-5429-4b97-b6c5-427936f00255.png)
がんばった

**Comment by taiyme** [comment]
爆速

**Comment by taiyme** [comment]
コケてるかも

<img width="544" alt="スクリーンショット 2023-02-26 8 54 17" src="https://user-images.githubusercontent.com/53635909/221384947-193d90b6-465c-4799-b63a-af64e478920f.png">

```
Create manifest and push
Error: The process '/usr/bin/docker' failed with exit code 1
```
とか言ってる

**Comment by cffnpwr** [comment]
どうやら複数のタグをもたせようとするとコケるらしい
今修正してる

**Comment by cffnpwr** [comment]
直ったのでPR飛ばす
