### ISSUE TITLE
特定の単語を含む投稿を禁止にする

### ISSUE THREAD

**Issue by taiyme** [taiyme/misskey#50]
## Summary
**たいわい** とか **NTR** とか禁止したほうがいいと思いまーす

## Summary2
現状 `$[x2` `$[x3` `$[x4` `$[scale` `$[position` が含まれるノートを投稿しようとすると警告が表示されるが、これを管理者が決められるようにするといいかも。

**Comment by taiyme** [comment]
鯖缶権限で設定する場合、やっぱりバックエンド側の改造が必要不可欠なんかな

**Comment by cffnpwr** [comment]
DBに新しいテーブルを生やす必要がありそう

**Comment by taiyme** [comment]
だよなあ

**Comment by cffnpwr** [comment]
misskey forkで新しいテーブル生やしてるところがあったはず

**Comment by taiyme** [comment]
新しいテーブル生やすならこれもやっておきたい
- https://github.com/taiyme/misskey/issues/26

**Comment by cffnpwr** [comment]
DBいじるならブランチ分けて開発したほうが良さそう

**Comment by cffnpwr** [comment]
ちなみにebisskeyでは[ここ](https://github.com/shrimpia/misskey/commit/dff482e7fd764bb783e34df83e8e0ef4ce94ae25)で新しいDB生やしてるっぽい
