### ISSUE TITLE
タイムライン以外ではRenote省略を無効にする

### ISSUE THREAD

**Issue by taiyme** [taiyme/misskey#53]
## Summary

https://submarin.online/notes/9brb025w5x

**Comment by cffnpwr** [comment]
これ実際の状況のスクショがほしいかも

**Comment by taiyme** [comment]
![image](https://user-images.githubusercontent.com/53635909/221754330-b58d68e2-1f6e-4e47-92ae-3300c22375e1.png)

**Comment by taiyme** [comment]
タイムラインでは省略されるべきで、ユーザーページなどでは展開されているべき…？

**Comment by cffnpwr** [comment]
そういうことだと思うけど、オプションとして省略と展開を選べるようにするべきかもしれない

**Comment by taiyme** [comment]
:kamo:

**Comment by taiyme** [comment]
MkNote.vueでRN省略を判定しているけど、コンポーネントからユーザーページにいることが判定できるのだろうか
