### ISSUE TITLE
リリースの自動化したい

### ISSUE THREAD

**Issue by cffnpwr** [taiyme/misskey#56]
## Summary
1. チェンジログを本文としたリリース用PRを作成
2. Github Actionsが動く
3. Dockerイメージのビルドが始まる
4. `package.json`の更新チェック
5. `docker-compose.yml`の`image: ghcr.io/taiyme/misskey:[tag]`を更新チェック
6. 更新されていなければ更新する
7. Dockerイメージのビルドが成功したら自動的にタグ打ってコミット
8. リリースする

みたいなフローを考えてる

**Comment by taiyme** [comment]
いいとおもう

**Comment by cffnpwr** [comment]
これに伴って`docker compose up -d`で起動時に手元でビルドさせるのをやめる

**Comment by cffnpwr** [comment]
バージョン名の指定どうしよう
- PRのタイトルに書く
- PRの本文にh1で書く
- [ここ](https://zenn.dev/team_zenn/articles/version-up-labeling)にあるみたいにlabelで管理する

**Comment by cffnpwr** [comment]
誰彼構わずリリースできてしまっては困るのでリポジトリオーナーのPRのみに制限するか

**Comment by taiyme** [comment]
誰彼構わずリリースできてしまっては困るな

**Comment by cffnpwr** [comment]
> バージョン名の指定どうしよう
> 
> * PRのタイトルに書く
> * PRの本文にh1で書く
> * [ここ](https://zenn.dev/team_zenn/articles/version-up-labeling)にあるみたいにlabelで管理する

これ、どれがいいですか

**Comment by taiyme** [comment]
これなあ
本文h1はとりあえず除外

**Comment by taiyme** [comment]
labelいいかも

**Comment by cffnpwr** [comment]
PR元のブランチを作らないといけなくなってきた

**Comment by cffnpwr** [comment]
あるいは`releases`みたいなリリースだけが乗るブランチを作っておいてそこへのPRにするとか
