### ISSUE TITLE
画像開いてるとき戻るボタンで閉じれるようにしてー

### ISSUE THREAD

**Issue by Midra429** [taiyme/misskey#58]
## Summary
https://submarin.online/notes/9bs1sxjjo1
https://submarin.online/notes/9bs1vy3tsw

**Comment by cffnpwr** [comment]
misskey-dev/misskeyだと
- https://github.com/misskey-dev/misskey/issues/10086
- https://github.com/misskey-dev/misskey/pull/10098
で修正されてるっぽい
