### ISSUE TITLE
ドロワー開いてるときも戻るボタンで閉じれるようにしてー

### ISSUE THREAD

**Issue by Midra429** [taiyme/misskey#59]
## Summary

https://github.com/taiyme/misskey/issues/58
これと同じ感じでモバイル表示でドロワー表示してるときも戻るボタンで閉じれるようにしてほしい

**Comment by cffnpwr** [comment]
これ、画像と同じように実装していいんだろうか

**Comment by cffnpwr** [comment]
絵文字ピッカーの形態の一つとしてドロワーが使われている感じなのでドロワーじゃない絵文字ピッカーも戻るボタンで閉じるようになる

**Comment by cffnpwr** [comment]
できたかもしれない

**Comment by taiyme** [comment]
:igyou:

**Comment by cffnpwr** [comment]
ノート投稿するときの画面も戻るボタンで閉じれたほうがいいんだろうか

**Comment by Midra429** [comment]
モーダルとかウィジェットのあれも戻るボタンで閉じれたほうがいいと思う

**Comment by cffnpwr** [comment]
今のところ（ドロワー表示の）モーダルは全部戻るで閉じるようにしてる

**Comment by cffnpwr** [comment]
これも戻るボタンで戻れるべき？
![image](https://user-images.githubusercontent.com/86540016/222215843-6a4d1164-5794-43ca-8fdd-0670acac264e.png)

**Comment by cffnpwr** [comment]
モバイル表示のときのウィジェットとメニューは別で定義されてるのでめんどうかも

**Comment by Midra429** [comment]
そこも戻るボタンで閉じれたほうがいいかも

**Comment by cffnpwr** [comment]
とりあえず後ろにブラーがかかる系のモーダルを全部戻るボタンで閉じるようにする

**Comment by cffnpwr** [comment]
モーダルのうえで更にモーダルが開く場合の処理が非常に面倒かも
