### ISSUE TITLE
Tabler Iconsを最新版にする

### ISSUE THREAD

**Issue by taiyme** [taiyme/misskey#7]
## Summary

[shield-filled](https://tabler-icons.io/i/shield-filled) を管理者用のアイコンとして使いたい

**Comment by taiyme** [comment]
なんかできんかったな(revert)

**Comment by cffnpwr** [comment]
[@tabler/icons](https://www.npmjs.com/package/@tabler/icons)の仕様がv1系とv2系で変わっていてv2はsvgになってるっぽい
vueのコンポーネントとしてtabler iconsが使える[@tabler/icons-vue](https://www.npmjs.com/package/@tabler/icons-vue)を使ったほうがいいかも

**Comment by cffnpwr** [comment]
もしくはwebfontとしてのtabler icons(https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css )を使うという手がある
こっちだと既存のコードをほとんど書き換えずにv2に移行が可能だが、ページロードの際に数秒の豆腐期間が発生する
あるいはビルドの際にwebfontをダウンロードしてファイルとして持っておくのも手かもしれない

**Comment by taiyme** [comment]
うーむ

**Comment by taiyme** [comment]
@tabler/icons-webfontというのがあるらしい
v13はこれっぽい？

**Comment by cffnpwr** [comment]
v13に追従する意味でも@tabler/icons-webfontにしよう
追ってPR飛ばす

**Comment by taiyme** [comment]
最新版にしたら全てのアイコンがやや左側にかたよってしまったので、とりあえずこのCSSを適用させておく

できればmisskey-dev/misskeyと合わせたいところだけど…

```css
.ti::before {
  display: inline-block;
  width: 1em;
}
```

**Comment by cffnpwr** [comment]
本家の修正コミットはおそらくこれ
https://github.com/misskey-dev/misskey/commit/8d3283e2a5dc49b9e9daa926c798efcb68bcec5e

**Comment by taiyme** [comment]
ちょいデカい

<img width="372" alt="スクリーンショット 2023-02-17 0 55 58" src="https://user-images.githubusercontent.com/53635909/219419124-166f95a6-303f-49fb-85bf-7e02e79c210b.png">

**Comment by cffnpwr** [comment]
なお、このコミットの修正を適用してもずれてる

**Comment by taiyme** [comment]
https://github.com/taiyme/misskey/issues/7#issuecomment-1433303472
もうこれでいい説ある

**Comment by cffnpwr** [comment]
多分それが正しい幅になってると思う
