### ISSUE TITLE
backend: 型定義をやり直す

### ISSUE THREAD

**Issue by taiyme** [taiyme/misskey#83]
## Summary
misskey-dev/misskeyのバーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

**Comment by cffnpwr** [comment]
大量に存在する`Prefer default export`の原因になってる[これ](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-default-export.md)の処分はどうする

**Comment by taiyme** [comment]
@cffnpwr issue分けるか
ここバックエンドにしてワイはフロントエンド側の方弄ってみる

**Comment by cffnpwr** [comment]
https://github.com/taiyme/misskey/blob/69942a7130f0b7ae510d568c7ef9e4d1bb0e084f/packages/backend/src/misc/get-note-summary.ts#L8
ここに`note.deletedAt`とあるが、型定義にもDBのスキーマにも`deletedAt`は存在しないのでどうにもできない
ちなみに本家ではv13に移行する際にDBのスキーマに`deletedAt`が生えてる

**Comment by taiyme** [comment]
ヌァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァンンンンオオオオンンオンオンオンオンンンンンンンンン゛ン゛！！！！！！！！！！！！！！！！

**Comment by cffnpwr** [comment]
とりあえずコメントアウトしておく

**Comment by taiyme** [comment]
おけ

**Comment by cffnpwr** [comment]
がんばったけどschemaのanyは殺せませんでした
型定義が循環していて謎だった
https://github.com/taiyme/misskey/blob/69942a7130f0b7ae510d568c7ef9e4d1bb0e084f/packages/backend/src/misc/schema.ts#L1-L172
