### ISSUE TITLE
prettierで`<template>`内のインデントをしないようにする

### ISSUE THREAD

**Issue by cffnpwr** [taiyme/misskey#84]
## Summary
`<script>`と`<style>`はできるんだから原理上できる

**Comment by cffnpwr** [comment]
これが動けばprettierでフォーマットができるようになる

**Comment by cffnpwr** [comment]
prettier自体を改造可能なら5分で終わるけどplugin作るとなると途端に難易度が上がりまくる

**Comment by cffnpwr** [comment]
prettierでのフォーマットをやめるかeslintでフォーマットするの2択になってきた

**Comment by taiyme** [comment]
prettierやめようぜ！

**Comment by cffnpwr** [comment]
eslintのフォーマット重すぎて使いたくないけど使うしかなさそう

**Comment by cffnpwr** [comment]
eslintの設定でフォーマットできる軽量なフォーマッタが現れたら復活させる
