### ISSUE TITLE
APIドキュメントを整備する

### ISSUE THREAD

**Issue by cffnpwr** [taiyme/misskey#90]
## Summary
- 既存のAPIドキュメント(instance.tld/api-doc)は不完全で、書いていないエンドポイントが存在する
- 既存のAPIドキュメントで使用されている[redoc](https://github.com/Redocly/redoc)は割と重いので軽いやつに変えたい

**Comment by taiyme** [comment]
api-docめちゃくちゃ重くて号泣しているとこだった

**Comment by cffnpwr** [comment]
スマホで開くとブラウザが固まって困るので早急になんとかしたい

**Comment by cffnpwr** [comment]
ざっとコード読んだりredocの仕様読んだりした結果
- エンドポイントにsecureオプションがあってこれがtrueだとリファレンスに乗らないようになってる（セキュリティ的に乗せるとまずいっぽい）
- /api-docはOpenAPIの定義を元にCSRしてるので重い→SSGできるのでなんとかなる
っていうことがわかった
